#! /usr/bin/env bash
# Modify next line and set destination drive to match mbed device
export LPC_DEPLOY='cp PROJECT.bin /Volumes/MBED/ ; sync'

SCRIPT_PATH=$0
SCRIPT_PATH=${SCRIPT_PATH%/*}
cd $SCRIPT_PATH
SCRIPT_PATH=$PWD
export
PATH=$SCRIPT_PATH/compiler/gcc-arm-none-eabi/bin:$SCRIPT_PATH/compiler/external/osx64:$PATH
exec bash --init-file ~/.profile
